# -*- coding: utf-8 -*-
"""20th_August_List_Based_Problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-M4ssfnax5p36GtR7i1DvOVPMQe5J_Ub

Create a list with integers from 1 to 10.
"""

l=[x for x in range(1,11)]
print(l)

"""Find the length of a list without using the `len()` function."""

l=list(map(int,input().split()))
c=0
for i in l:
  c+=1
print("Length of the string is:",c)

"""Append an element to the end of a list."""

l=list(map(int,input().split()))
a=input("Enter the element to append:")
l.append(a)
print(l)

"""Insert an element at a specific index in a list."""

l=list(map(int,input().split()))
a=input("Enter the element to insert:")
index=int(input("Enter the index to insert the element:"))
l.insert(index,a)
print(l)

"""5. Remove an element from a list by its value."""

l = list(map(int, input().split()))
a = input("Enter the element to remove:")

if int(a) in l:
    l.remove(int(a))
else:
    print(f"{a} is not in the list.")

print(l)

"""Remove an element from a list by its index."""

l = list(map(int, input().split()))
a = input("Enter the index of the element  to remove:")

if int(a) in l:
    l.pop(int(a))
else:
    print(f"{a} is not in the list.")

print(l)

"""Check if an element exists in a list.

"""

l = list(map(int, input().split()))
a = input("Enter the element  to check:")
if int(a) in l:
  print(a,"is present in the list")
else:
  print(a,"is not present in the list")

"""Find the index of the first occurrence of an element in a list."""

l = list(map(int, input().split()))
a = input("Enter the element  to find the first occurrence:")
print(l.index(int(a)))

"""Count the occurrences of an element in a list."""

l = list(map(int, input().split()))
a = input("Enter the element  to find its occurrence:")

print(l.count(int(a)))

"""Reverse the order of elements in a list."""

l = list(map(int, input().split()))
print(l[::-1])

"""Sort a list in ascending order."""

l = list(map(int, input().split()))
l.sort()
print(l)

"""Sort a list in descending order."""

l = list(map(int, input().split()))
l.sort(reverse=True)
print(l)

"""Create a list of even numbers from 1 to 20."""

l=[x  for x in range(1,21) if x%2==0]
print(l)

"""Create a list of odd numbers from 1 to 20."""

l=[x  for x in range(1,21) if x%2==1]
print(l)

"""Find the sum of all elements in a list."""

l=[i for i in range(1,20)]
print(sum(l))

"""Find the maximum value in a list."""

l=list(map(int, input().split()))
print("Maximum value in the list is:",max(l))

"""Find the minimum value in a list."""

l=list(map(int, input().split()))
print("Minimum value in the list is:",min(l))

"""Create a list of squares of numbers from 1 to 10."""

l=[i**2 for i in range(1,11)]
print(l)

"""Create a list of random numbers."""

import random
l=random.sample(range(1,100),10)
print(l)

"""Remove duplicates from a list."""

l=list(map(int, input().split()))
dup=[]
for i in l:
  if i in dup:
    continue
  else:
    dup.append(i)
print("List after removing the duplicates:",dup)

"""Find the common elements between two lists."""

import random
l=random.sample(range(1,30),20)
m=[x for x in range(20)]
print("List1:",l)
print("List2:",m)
for i in l:
  if i in m:
    print(i,end=" ")

"""Find the difference between two lists."""

import random
l=random.sample(range(1,30),20)
m=[x for x in range(20)]
print("List1:",l)
print("List2:",m)
for i in l:
  if i not in m:
    print(i,end=" ")

import random
l=random.sample(range(1,30),20)
m=[x for x in range(20)]
print(l)
print(m)
l.extend(m)
print(l)

"""Multiply all elements in a list by 2."""

l=random.sample(range(1,30),10)
print(l)
l2=[x*2 for x in l]
print(l2)

"""Filter out all even numbers from a list."""

import random

def even(num):
    return num % 2 == 0

l = random.sample(range(1, 30), 10)
f = list(filter(even, l))
print(f)

"""Convert a list of strings to a list of integers."""

s=input().split()
for i in range(len(s)):
  s[i]=len(s[i])

print(s)

"""Convert a list of integers to a list of strings."""

l=list(map(int, input().split()))
for i in range(len(l)):
  l[i]=str(l[i])
print(l)

"""Flatten a nested list."""

l=[[1,2,3],[4,5,6],[7,8,9]]
m=[]
for i in l:
  m.extend(i)
print(m)
print(len(m))

"""Create a list of the first 10 Fibonacci numbers."""

a=0
b=1
l=[0,1]
n=int(input("Enter the number upto which you want the fibonacci:"))
def fib(a,b):
  for i in range(n):
    c=a+b
    l.append(c)
    a=b
    b=c
fib(a,b)
print(l)

def fibo(n):
  if n<=1:
    return n
  else:
    return fibo(n-2)+fibo(n-1)

fibo(5)

"""Check if a list is sorted."""

l=list(map(int, input().split()))
a=input("Enter the sorting order you want to check: as/ds? ")
def sorted_as(l):

  for i in range(len(l)-1):
    if l[i]>l[i+1]:
      return False
  return True
def sorted_ds(l):
  for i in range(len(l)-1):
    if l[i]<l[i+1]:
      return False
  return True

if a.lower()=='as':
  print(sorted_as(l))
elif a.lower()=='ds':
  print(sorted_ds(l))
else:
  print("Enter valid input:")

"""Rotate a list to the left by `n` positions."""

l=list(map(int, input().split()))
k=int(input("Enter the number of position to rotate the  list to left:"))
for j in range(k):
  first=l[0]
  for i in range(len(l)-1):
    l[i]=l[i+1]
  l[-1]=first

print(l)

"""Rotate a list to the right by `n` positions."""

l=list(map(int, input().split()))
k=int(input("Enter the number of position to rotate the  list to right:"))
for j in range(k):
  last=l[-1]
  for i in range((len(l)-2),-1,-1):
    l[i+1]=l[i]
  l[0]=last

print(l)

"""Create a list of prime numbers up to 50."""

l=[]
n=int(input("Enter the range upto which you want to find the prime number:"))
for i in range(2,n+1):
  c=0


  for j in range(2,i//2+1):
    if i%j==0:
      c=c+1
  if c==0:
    l.append(i)

print(l)

"""Split a list into chunks of size `n`."""

l = [1, 2, 3, 4, 5, 6, 7, 8, 9]


n = int(input())


x = [l[i:i + n] for i in range(0, len(l), n)]
print(x)

"""Find the second largest number in a list."""

l=list(map(int,input().split()))
l.remove(max(l))
print('second largest number in the list is:',max(l))

"""Replace every element in a list with its square."""

l=list(map(int,input().split()))
def square(n):
  return n*n

print(list(map(square,l)))

"""Convert a list to a dictionary where list elements become keys and their
indices become values.
"""

l=list(map(int,input().split()))
d={}
for i in range(len(l)):
  d[i]=l[i]

print(d)

"""Shuffle the elements of a list randomly."""

import random
l=list(map(int, input().split()))
for i in range(5):
  print(random.sample(l,len(l)))

"""Create a list of the first 10 factorial numbers."""

l=[]
def fac(n):
  if n<=1:
    return n
  else:
    return n*fac(n-1)
for i in range(1,11):
  l.append(fac(i))

print(l)

"""Check if two lists have at least one element in common."""

l1=list(map(int,input().split()))
l2=list(map(int,input().split()))
c=0
for i in l1:
  for j in l2:
    if i==j:
      c+=1
print(c,"elements in the above lists are common")

"""Remove all elements from a list."""

l=list(map(int, input().split()))
for i in range(len(l)):
  l.pop()
print(l)

"""Replace negative numbers in a list with 0."""

l=list(map(int, input().split()))
for i in range(len(l)):
  if l[i]<0:
    l[i]=0
  else:
    continue
print(l)

"""Convert a string into a list of words."""

s=input("Enter the string:")
l=list(s)
print(l)

"""Convert a string into a list of words."""

l=list(map(str,input().split()))
s=''
s=s.join(l)
print(s)

"""Create a list of the first `n` powers of 2."""

n=int(input("Enter the value upto which you want to find the power of 2:"))
l=[]
for i in range(n+1):
  l.append(2**i)

print(l)

"""Find the longest string in a list of strings."""

l=list(map(str,input().split()))
def length(s):
  return len(s)
m=list(map(length,l))
for i in l:
  if len(i)==max(m):
    print(i)

"""Find the shortest string in a list of strings."""

l=list(map(str,input().split()))
def length(s):
  return len(s)
m=list(map(length,l))
for i in l:
  if len(i)==min(m):
    print(i)

"""Create a list of the first `n` triangular numbers."""

n=int(input("Enter the number of traingular number you want:"))
l=[]
def tri(n):
  if n<0:
    return False
  sum,num=0,1
  while(sum<=n):
    sum=sum+num
    if sum==n:
      return True
    num+=1
  return False

for i in range(n+1):
  if tri(i):
    l.append(i)

print(l)

"""Check if a list contains another list as a subsequence."""

l1=list(map(int,input().split()))
l2=list(map(int,input().split()))

if set(l2) & set(l1)==set(l2):
  print("True")
else:
  print("False")

"""Swap two elements in a list by their indices."""

l=list(map(int, input().split()))
index=int(input("Enter the index of the number to swap:"))
index2=int(input("Enter the index of the 2nd number to be swapped:"))
if index>=len(l) or index2>=len(l):
  print("invalid index")
else:
  a=l[index]
  l[index]=l[index2]
  l[index2]=a
print(l)

